services:
    anca_rebeca_full_calendar.service.serializer:
        class: AncaRebeca\FullCalendarBundle\Service\Serializer
        public: false

    anca_rebeca_full_calendar.service.calendar:
        class: AncaRebeca\FullCalendarBundle\Service\Calendar
        public: false
        arguments:
            - @event_dispatcher
            - @anca_rebeca_full_calendar.service.serializer
